server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
    level:
      org:
        apache:
          ibatis: debug
      java:
        sql: debug